-- ============================================================
-- whatsapp_config: add UAZAPI as a second connection provider
--
-- Until now every row assumed the Meta Cloud API: `phone_number_id`
-- and `access_token` were NOT NULL. UAZAPI (unofficial, QR-code
-- based) has no equivalent of either — it identifies a connection by
-- a `session` name + `sessionkey`, both generated by this app (never
-- typed by the user). See docs/superpowers/specs/2026-08-03-uazapi-provider-design.md.
--
-- `provider` discriminates which set of columns is authoritative for
-- a row. Defaults to 'meta' so every existing row is valid the
-- instant this migration runs, with no backfill required.
--
-- `uazapi_status` is a separate column (not a widened `status` CHECK)
-- because UAZAPI's own states (notLogged, STARTING, inChat,
-- disconnectedMobile, ...) don't map cleanly onto the existing
-- connected/disconnected pair, and collapsing them would throw away
-- diagnostic information the UI wants to show verbatim.
--
-- `uazapi_session` gets its own UNIQUE constraint for the same reason
-- migration 013 added one on `phone_number_id`: the UAZAPI inbound
-- webhook route will look up the owning account by `uazapi_session`
-- with `.single()`, and a duplicate would make it silently drop every
-- inbound message for both accounts.
--
-- Idempotent — safe to run multiple times.
-- ============================================================

-- 1. provider discriminator, defaulting every existing row to 'meta'.
ALTER TABLE whatsapp_config
  ADD COLUMN IF NOT EXISTS provider TEXT NOT NULL DEFAULT 'meta';

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'whatsapp_config_provider_check'
      AND conrelid = 'whatsapp_config'::regclass
  ) THEN
    ALTER TABLE whatsapp_config
      ADD CONSTRAINT whatsapp_config_provider_check
      CHECK (provider IN ('meta', 'uazapi'));
  END IF;
END $$;

-- 2. Meta fields become optional — a 'uazapi' row has neither.
--    DROP NOT NULL is a no-op (no error) if already nullable, so this
--    is safe to re-run.
ALTER TABLE whatsapp_config
  ALTER COLUMN phone_number_id DROP NOT NULL,
  ALTER COLUMN access_token DROP NOT NULL;

-- 3. UAZAPI-specific fields.
ALTER TABLE whatsapp_config
  ADD COLUMN IF NOT EXISTS uazapi_session TEXT,
  ADD COLUMN IF NOT EXISTS uazapi_session_key TEXT,
  ADD COLUMN IF NOT EXISTS uazapi_status TEXT,
  ADD COLUMN IF NOT EXISTS uazapi_connected_phone TEXT;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'whatsapp_config_uazapi_session_unique'
      AND conrelid = 'whatsapp_config'::regclass
  ) THEN
    ALTER TABLE whatsapp_config
      ADD CONSTRAINT whatsapp_config_uazapi_session_unique
      UNIQUE (uazapi_session);
  END IF;
END $$;

-- 4. Coherence check: a row's provider dictates which fields are
--    required. Prevents a half-configured row of either kind from
--    ever being saved, at the DB layer (not just app validation).
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'whatsapp_config_provider_fields_check'
      AND conrelid = 'whatsapp_config'::regclass
  ) THEN
    ALTER TABLE whatsapp_config
      ADD CONSTRAINT whatsapp_config_provider_fields_check
      CHECK (
        (provider = 'meta'
          AND phone_number_id IS NOT NULL
          AND access_token IS NOT NULL)
        OR
        (provider = 'uazapi'
          AND uazapi_session IS NOT NULL
          AND uazapi_session_key IS NOT NULL)
      );
  END IF;
END $$;
